import Pamela from '../assets/local.webp'
import Rocky from '../assets/local2.webp'
import Emporio_SM from '../assets/local3.webp'

export const Locals = [
    {
        id: 1,
        title: 'Pamela',
        category: 'Minimarket',
        address: 'Diaguitas 507',
        time: '60min',
        stars: '5',
        img: Pamela,
    },
    {
        id: 2,
        title: 'Rocky',
        category: 'Minimarket',
        address: 'Diaguitas 507',
        time: '60min',
        stars: '5',
        img: Rocky,
    },
    {
        id: 3,
        title: 'Emporio SM',
        category: 'Minimarket',
        address: 'Diaguitas 507',
        time: '60min',
        stars: '5',
        img: Emporio_SM,
    },
    {
        id: 4,
        title: 'Pamela',
        category: 'Minimarket',
        address: 'Diaguitas 507',
        time: '60min',
        stars: '5',
        img: Pamela,
    },
    {
        id: 5,
        title: 'Rocky',
        category: 'Minimarket',
        address: 'Diaguitas 507',
        time: '60min',
        stars: '5',
        img: Rocky,
    },
    {
        id: 6,
        title: 'Emporio SM',
        category: 'Minimarket',
        address: 'Diaguitas 507',
        time: '60min',
        stars: '5',
        img: Emporio_SM,
    },
    {
        id: 7,
        title: 'Pamela',
        category: 'Minimarket',
        address: 'Diaguitas 507',
        time: '60min',
        stars: '5',
        img: Pamela,
    },
    {
        id: 8,
        title: 'Rocky',
        category: 'Minimarket',
        address: 'Diaguitas 507',
        time: '60min',
        stars: '5',
        img: Rocky,
    },
    {
        id: 9,
        title: 'Emporio SM',
        category: 'Minimarket',
        address: 'Diaguitas 507',
        time: '60min',
        stars: '5',
        img: Emporio_SM,
    },
    {
        id: 10,
        title: 'Pamela',
        category: 'Minimarket',
        address: 'Diaguitas 507',
        time: '60min',
        stars: '5',
        img: Pamela,
    },
    {
        id: 11,
        title: 'Rocky',
        category: 'Minimarket',
        address: 'Diaguitas 507',
        time: '60min',
        stars: '5',
        img: Rocky,
    },
    {
        id: 12,
        title: 'Emporio SM',
        category: 'Minimarket',
        address: 'Diaguitas 507',
        time: '60min',
        stars: '5',
        img: Emporio_SM,
    },
]